helloPro:
  ribbon:
    listOfServers: localhost:1001,localhost:1002
#    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RoundRobinRule
#    NFLoadBalancerRuleClassName: com.gateway.config.MyRule
#    NFLoadBalancerPingClassName: com.yefengyu.gateway.loadbanlance.HealthExamination


demoPro:
  ribbon:
    listOfServers: localhost:1003,localhost:1004
    #    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RoundRobinRule
    #    NFLoadBalancerRuleClassName: com.gateway.config.MyRule
#    NFLoadBalancerPingClassName: com.yefengyu.gateway.loadbanlance.HealthExamination
server:
  port: 8080
spring:
  application:
    name: gateway_server
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
          lowerCaseServiceId: true

      #      default-filters:
      routes:
      - id: helloPro
#          uri: http://localhost:1001/
        uri: lb://helloPro
        predicates:
          - Path=/helloPro/**
#        filters:
#          - StripPrefix=1
      - id: demoPro
        uri: lb://demoPro
        predicates:
          - Path=/demoPro/**
#        filters:
#          - StripPrefix=1